Repository ajayyy/SponsorBlock, pull requests merged in 2019-08, with the labels that each got.

#86 Multilingual support [TESTING]
  _locales/en/messages.json
  background.js
  content.js
  help/index_en.html
  manifest.json
  popup.js
  popup_en.html
Labels: almost ready to merge, stuck

#123 Russian translation
  _locales/ru/messages.json
Labels: translation

#83 Added youtube-nocookie.com
  manifest.json
Labels: not ready
